/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EventCntl;
import model.Event;

/**
 *
 * @author taesankim
 */
public class EventUI extends javax.swing.JFrame {
    private EventCntl eventCntl;
    private Event event;
    private int currentSelectedRow;
    /**
     * Creates new form AssignmentUI
     */
    
    public EventUI(EventCntl eventCntl, Event event) {
        this.eventCntl = eventCntl;
        this.event = event;
        initComponents();
        parseCurrentEvent();
    }
    public EventUI(EventCntl eventCntl, int selectedRow) {
        this.eventCntl = eventCntl;
        currentSelectedRow = selectedRow;
        event = eventCntl.getEvent(selectedRow);
        this.event = event;
        initComponents();
        parseCurrentEvent();
    }
    
    public void updateData (Event event) {
        this.event = event;
        parseCurrentEvent();
    }
    
    public void parseCurrentEvent() {
        title.setText("" + event.getSerialNumber());
        startdate.setText(event.getStartDate());
        enddate.setText(event.getEndDate());
        serialNum.setText(event.getSerialNumber());
        categories.setText(event.getCategories());
        description.setText(event.getDescription());
                
    }
    public void newData() {
        title.setText("");
        startdate.setText("");
        enddate.setText("");
        serialNum.setText("");
        categories.setText("");
        description.setText("");
    }
    
    public String getTitle() {
        return title.getText();
    }
    public String getStartDate() {
        return startdate.getText();
    }
    public String getEndDate() {
        return enddate.getText();
    }
    public String getSerialNum() {
        return serialNum.getText();
    }
    public String getCategories() {
        return categories.getText();
    }
    public String getDescription() {
        return description.getText();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titleç = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        startdate = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        prevBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        serialNumLabel = new javax.swing.JLabel();
        enddate = new javax.swing.JTextField();
        serialNum = new javax.swing.JTextField();
        categoriesLabel = new javax.swing.JLabel();
        categories = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Assignment");

        titleç.setText("Title:");

        startDateLabel.setText("Start Date:");

        endDateLabel.setText("End Date:");

        descriptionLabel.setText("Description:");

        prevBtn.setText("Previous");

        nextBtn.setText("Next");

        serialNumLabel.setText("Serial Number:");

        categoriesLabel.setText("Categories:");

        updateBtn.setText("Update");

        addBtn.setText("Add");

        deleteBtn.setText("Delete");

        quitBtn.setText("Quit");

        cancelBtn.setText("Cancel");

        saveBtn.setText("Save");

        backBtn.setText("Back");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionLabel)
                            .addComponent(categoriesLabel))
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addGap(49, 49, 49)
                                .addComponent(cancelBtn))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(prevBtn)
                                .addGap(18, 18, 18)
                                .addComponent(nextBtn)
                                .addGap(28, 28, 28)
                                .addComponent(updateBtn)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(27, 27, 27)
                                .addComponent(quitBtn))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serialNumLabel)
                            .addComponent(endDateLabel)
                            .addComponent(startDateLabel)
                            .addComponent(titleç))
                        .addGap(82, 82, 82)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categories)
                            .addComponent(title)
                            .addComponent(startdate)
                            .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(enddate)
                            .addComponent(serialNum))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleç))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startdate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabel))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNumLabel))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriesLabel))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionLabel))
                .addGap(83, 83, 83)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevBtn)
                    .addComponent(nextBtn)
                    .addComponent(updateBtn)
                    .addComponent(addBtn)
                    .addComponent(deleteBtn))
                .addGap(38, 38, 38)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitBtn)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn)
                    .addComponent(backBtn))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    public javax.swing.JButton addBtn;
    public javax.swing.JButton backBtn;
    public javax.swing.JButton cancelBtn;
    private javax.swing.JTextField categories;
    private javax.swing.JLabel categoriesLabel;
    public javax.swing.JButton deleteBtn;
    private javax.swing.JTextField description;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField enddate;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton nextBtn;
    public javax.swing.JButton prevBtn;
    public javax.swing.JButton quitBtn;
    public javax.swing.JButton saveBtn;
    private javax.swing.JTextField serialNum;
    private javax.swing.JLabel serialNumLabel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startdate;
    private javax.swing.JTextField title;
    private javax.swing.JLabel titleç;
    public javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
